Development/testing
Unity-Technologies/roslyn pull request #11
Opened 2020-01-13 16:16 UTC by domenico-villani

- a shell script that'll make the Stevedore artifact zips

- a new Yamato YAML file for a "Publish Stevedore artifacts" Yamato job that automatically uploads stevedore artifacts after Roslyn is built, it uploads to testing for now

2020-01-13 20:49 UTC, kwi-dk reviewed
Added some comments.

2020-01-13 20:49 UTC, kwi-dk commented on .yamato/publish_stevedore_artifacts.yml
> +  - sudo apt-get install -y p7zip-full p7zip-rar
I see on Yamato that the image already has p7zip-full:
> p7zip-full is already the newest version (16.02+dfsg-6).

And you surely don't need RAR support? So you can skip this step entirely.

2020-01-13 20:49 UTC, kwi-dk commented on .yamato/test.yml
> +name: 'Test Mono Upload'
This entire file should presumably just be deleted, now you're done testing?

2020-01-13 20:49 UTC, kwi-dk commented on stevedore-build-artifacts.sh
> +sudo chmod -v +x Artifacts/Builds/Binaries/Linux/csc
I don't think you need `sudo`, the entire script should already be running as root? (And if not, you should still not need root to set the execute bit.)

2020-01-13 20:49 UTC, kwi-dk commented on stevedore-build-artifacts.sh
> +done
This seems like a lot of work just to print out the artifact IDs. `StevedoreUpload.exe` already prints out the artifact IDs upon successful upload, e.g.:

    Artifact uploaded successfully:
        testing: roslyn-csc-linux/41f6ba9d99e7_6b3d1c740d0840e1eb1c58421ffe3ad5cf5c9e25c70e5ec78550bd42daa08dde.7z

Seems like you can remove all this, and then don't need to pass any arguments when running the script either.

2020-01-13 20:49 UTC, kwi-dk commented on .yamato/publish_stevedore_artifacts.yml
> +name: 'Publish 7z Stevedore artifacts'
That should be "Publish roslyn-csc Stevedore artifacts" or something like that. :)

2020-01-15 09:20 UTC, domenico-villani commented on .yamato/publish_stevedore_artifacts.yml
> +  - sudo apt-get install -y p7zip-full p7zip-rar
done

2020-01-16 17:42 UTC, kwi-dk requested changes
One final comment, then we'll look at landing it.

2020-01-16 17:42 UTC, kwi-dk commented on .yamato/publish_roslyn-csc_stevedore_artifacts.yml
>    # Script needs the version string of the source artifact (which must match StevedoreUpload args).
This comment is no longer valid.

2020-01-20 15:43 UTC, kwi-dk requested changes
One more.

2020-01-20 15:43 UTC, kwi-dk commented on stevedore-build-artifacts.sh
> +7z a producedbuilds/roslyn-csc-net46.7z $PWD/Artifacts/Builds/Binaries/Net46/*
It occurs to me that this is not adding a LICENSE file to the artifacts (per the artifact guidelines, "All artifacts must contain a LICENSE file in their root"... even if our current csc artifacts are possibly also missing this). You can simply use the existing License.txt from the Roslyn repo (though the filename must be changed to uppercase): it should be enough to simply run
```cp License.txt $PWD/Artifacts/Builds/Binaries/Linux/LICENSE.txt```
(etc., for each of the four artifacts), _before_ 7z.

2020-02-04 15:44 UTC, kwi-dk commented
Superseded by #12.

2020-02-04 15:44 UTC, closed without merging